/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import type { EditorThemeClasses } from "lexical";

import "./NoteTheme.css";

const theme: EditorThemeClasses = {
  autocomplete: "NoteTheme__autocomplete",
  blockCursor: "NoteTheme__blockCursor",
  characterLimit: "NoteTheme__characterLimit",
  code: "NoteTheme__code",
  // codeHighlight: {
  //   atrule: 'NoteTheme__tokenAttr',
  //   attr: 'NoteTheme__tokenAttr',
  //   boolean: 'NoteTheme__tokenProperty',
  //   builtin: 'NoteTheme__tokenSelector',
  //   cdata: 'NoteTheme__tokenComment',
  //   char: 'NoteTheme__tokenSelector',
  //   class: 'NoteTheme__tokenFunction',
  //   'class-name': 'NoteTheme__tokenFunction',
  //   comment: 'NoteTheme__tokenComment',
  //   constant: 'NoteTheme__tokenProperty',
  //   deleted: 'NoteTheme__tokenProperty',
  //   doctype: 'NoteTheme__tokenComment',
  //   entity: 'NoteTheme__tokenOperator',
  //   function: 'NoteTheme__tokenFunction',
  //   important: 'NoteTheme__tokenVariable',
  //   inserted: 'NoteTheme__tokenSelector',
  //   keyword: 'NoteTheme__tokenAttr',
  //   namespace: 'NoteTheme__tokenVariable',
  //   number: 'NoteTheme__tokenProperty',
  //   operator: 'NoteTheme__tokenOperator',
  //   prolog: 'NoteTheme__tokenComment',
  //   property: 'NoteTheme__tokenProperty',
  //   punctuation: 'NoteTheme__tokenPunctuation',
  //   regex: 'NoteTheme__tokenVariable',
  //   selector: 'NoteTheme__tokenSelector',
  //   string: 'NoteTheme__tokenSelector',
  //   symbol: 'NoteTheme__tokenProperty',
  //   tag: 'NoteTheme__tokenProperty',
  //   url: 'NoteTheme__tokenOperator',
  //   variable: 'NoteTheme__tokenVariable',
  // },
  codeHighlight: {
    atrule: "dracula-purple",
    attr: "dracula-purple",
    boolean: "dracula-purple",
    builtin: "dracula-purple",
    cdata: "dracula-pink",
    char: "dracula-yellow",
    class: "dracula-cyan",
    "class-name": "dracula-current-line",
    comment: "dracula-comment",
    constant: "dracula-purple",
    deleted: "dracula-red",
    doctype: "dracula-comment",
    entity: "dracula-pink",
    function: "dracula-pink",
    important: "dracula-foreground",
    inserted: "dracula-green",
    keyword: "dracula-pink",
    namespace: "dracula-purple",
    number: "dracula-purple",
    operator: "dracula-pink",
    prolog: "dracula-comment",
    property: "dracula-purple",
    punctuation: "dracula-foreground",
    regex: "dracula-red",
    selector: "dracula-pink",
    string: "dracula-yellow",
    symbol: "dracula-purple",
    tag: "dracula-pink",
    url: "dracula-cyan",
    variable: "dracula-foreground",
  },
  embedBlock: {
    base: "NoteTheme__embedBlock",
    focus: "NoteTheme__embedBlockFocus",
  },
  hashtag: "NoteTheme__hashtag",
  heading: {
    h1: "text-3xl font-extrabold",
    h2: "text-2xl font-bold",
    h3: "text-xl font-bold",
    h4: "text-lg font-bold",
    h5: "font-bold",
    h6: "font-semibold",
  },
  hr: "NoteTheme__hr",
  image: "editor-image",
  indent: "NoteTheme__indent",
  inlineImage: "inline-editor-image",
  layoutContainer: "NoteTheme__layoutContainer",
  layoutItem: "NoteTheme__layoutItem",
  link: "NoteTheme__link",
  // list: {
  //   checklist: "NoteTheme__checklist",
  //   listitem: "NoteTheme__listItem",
  //   listitemChecked: "NoteTheme__listItemChecked",
  //   listitemUnchecked: "NoteTheme__listItemUnchecked",
  //   nested: {
  //     listitem: "NoteTheme__nestedListItem",
  //   },
  //   olDepth: [
  //     "NoteTheme__ol1",
  //     "NoteTheme__ol2",
  //     "NoteTheme__ol3",
  //     "NoteTheme__ol4",
  //     "NoteTheme__ol5",
  //   ],
  //   ul: "NoteTheme__ul",
  // },
  list: {
    checklist: "",
    listitemChecked: "NoteTheme__listItemChecked",
    listitemUnchecked: "NoteTheme__listItemUnchecked",
    nested: {
      listitem: "list-none",
    },
    olDepth: [
      "list-outside list-decimal",
      "m-0 p-0 list-outside list-[upper-alpha]",
      "m-0 p-0 list-outside list-[lower-alpha]",
      "m-0 p-0 list-outside list-[upper-roman]",
      "m-0 p-0 list-outside list-[lower-roman]",
    ],
    ul: "ml-4 space-y-1 list-disc list-outside",
    listitem: "ml-4 marker:text-muted-foreground ",
  },
  ltr: "text-left",
  mark: "NoteTheme__mark",
  markOverlap: "NoteTheme__markOverlap",
  paragraph: "NoteTheme__paragraph",
  quote: "NoteTheme__quote",
  rtl: "text-right",
  table: "NoteTheme__table",
  tableAddColumns: "NoteTheme__tableAddColumns",
  tableAddRows: "NoteTheme__tableAddRows",
  tableCell: "NoteTheme__tableCell",
  tableCellActionButton: "NoteTheme__tableCellActionButton",
  tableCellActionButtonContainer: "NoteTheme__tableCellActionButtonContainer",
  tableCellEditing: "NoteTheme__tableCellEditing",
  tableCellHeader: "NoteTheme__tableCellHeader",
  tableCellPrimarySelected: "NoteTheme__tableCellPrimarySelected",
  tableCellResizer: "NoteTheme__tableCellResizer",
  tableCellSelected: "NoteTheme__tableCellSelected",
  tableCellSortedIndicator: "NoteTheme__tableCellSortedIndicator",
  tableResizeRuler: "NoteTheme__tableCellResizeRuler",
  tableSelected: "NoteTheme__tableSelected",
  tableSelection: "NoteTheme__tableSelection",
  text: {
    bold: "font-bold",
    code: "font-mono text-[94%] bg-secondary p-1 rounded-md",
    italic: "italic",
    strikethrough: "line-through",
    subscript: "sub",
    superscript: "sup",
    underline: "underline",
    underlineStrikethrough: "line-through underline",
  },
};

export default theme;
