/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import type { EditorThemeClasses } from "lexical";

import "./PlaygroundEditorTheme.css";

const theme: EditorThemeClasses = {
  autocomplete: "PlaygroundEditorTheme__autocomplete",
  blockCursor: "PlaygroundEditorTheme__blockCursor",
  characterLimit: "PlaygroundEditorTheme__characterLimit",
  code: "PlaygroundEditorTheme__code",
  // codeHighlight: {
  //   atrule: 'PlaygroundEditorTheme__tokenAttr',
  //   attr: 'PlaygroundEditorTheme__tokenAttr',
  //   boolean: 'PlaygroundEditorTheme__tokenProperty',
  //   builtin: 'PlaygroundEditorTheme__tokenSelector',
  //   cdata: 'PlaygroundEditorTheme__tokenComment',
  //   char: 'PlaygroundEditorTheme__tokenSelector',
  //   class: 'PlaygroundEditorTheme__tokenFunction',
  //   'class-name': 'PlaygroundEditorTheme__tokenFunction',
  //   comment: 'PlaygroundEditorTheme__tokenComment',
  //   constant: 'PlaygroundEditorTheme__tokenProperty',
  //   deleted: 'PlaygroundEditorTheme__tokenProperty',
  //   doctype: 'PlaygroundEditorTheme__tokenComment',
  //   entity: 'PlaygroundEditorTheme__tokenOperator',
  //   function: 'PlaygroundEditorTheme__tokenFunction',
  //   important: 'PlaygroundEditorTheme__tokenVariable',
  //   inserted: 'PlaygroundEditorTheme__tokenSelector',
  //   keyword: 'PlaygroundEditorTheme__tokenAttr',
  //   namespace: 'PlaygroundEditorTheme__tokenVariable',
  //   number: 'PlaygroundEditorTheme__tokenProperty',
  //   operator: 'PlaygroundEditorTheme__tokenOperator',
  //   prolog: 'PlaygroundEditorTheme__tokenComment',
  //   property: 'PlaygroundEditorTheme__tokenProperty',
  //   punctuation: 'PlaygroundEditorTheme__tokenPunctuation',
  //   regex: 'PlaygroundEditorTheme__tokenVariable',
  //   selector: 'PlaygroundEditorTheme__tokenSelector',
  //   string: 'PlaygroundEditorTheme__tokenSelector',
  //   symbol: 'PlaygroundEditorTheme__tokenProperty',
  //   tag: 'PlaygroundEditorTheme__tokenProperty',
  //   url: 'PlaygroundEditorTheme__tokenOperator',
  //   variable: 'PlaygroundEditorTheme__tokenVariable',
  // },
  codeHighlight: {
    atrule: "dracula-purple",
    attr: "dracula-purple",
    boolean: "dracula-purple",
    builtin: "dracula-purple",
    cdata: "dracula-pink",
    char: "dracula-yellow",
    class: "dracula-cyan",
    "class-name": "dracula-current-line",
    comment: "dracula-comment",
    constant: "dracula-purple",
    deleted: "dracula-red",
    doctype: "dracula-comment",
    entity: "dracula-pink",
    function: "dracula-pink",
    important: "dracula-foreground",
    inserted: "dracula-green",
    keyword: "dracula-pink",
    namespace: "dracula-purple",
    number: "dracula-purple",
    operator: "dracula-pink",
    prolog: "dracula-comment",
    property: "dracula-purple",
    punctuation: "dracula-foreground",
    regex: "dracula-red",
    selector: "dracula-pink",
    string: "dracula-yellow",
    symbol: "dracula-purple",
    tag: "dracula-pink",
    url: "dracula-cyan",
    variable: "dracula-foreground",
  },
  embedBlock: {
    base: "PlaygroundEditorTheme__embedBlock",
    focus: "PlaygroundEditorTheme__embedBlockFocus",
  },
  hashtag: "PlaygroundEditorTheme__hashtag",
  // heading: {
  //   h1: "PlaygroundEditorTheme__h1",
  //   h2: "PlaygroundEditorTheme__h2",
  //   h3: "PlaygroundEditorTheme__h3",
  //   h4: "PlaygroundEditorTheme__h4",
  //   h5: "PlaygroundEditorTheme__h5",
  //   h6: "PlaygroundEditorTheme__h6",
  // },
  heading: {
    h1: "text-3xl font-extrabold",
    h2: "text-2xl font-bold",
    h3: "text-xl font-bold",
    h4: "text-lg font-bolde",
    h5: "font-bold",
  },
  hr: "PlaygroundEditorTheme__hr",
  image: "editor-image",
  indent: "PlaygroundEditorTheme__indent",
  inlineImage: "inline-editor-image",
  layoutContainer: "PlaygroundEditorTheme__layoutContainer",
  layoutItem: "PlaygroundEditorTheme__layoutItem",
  link: "PlaygroundEditorTheme__link",
  // list: {
  //   checklist: "PlaygroundEditorTheme__checklist",
  //   listitem: "PlaygroundEditorTheme__listItem",
  //   listitemChecked: "PlaygroundEditorTheme__listItemChecked",
  //   listitemUnchecked: "PlaygroundEditorTheme__listItemUnchecked",
  //   nested: {
  //     listitem: "PlaygroundEditorTheme__nestedListItem",
  //   },
  //   olDepth: [
  //     "PlaygroundEditorTheme__ol1",
  //     "PlaygroundEditorTheme__ol2",
  //     "PlaygroundEditorTheme__ol3",
  //     "PlaygroundEditorTheme__ol4",
  //     "PlaygroundEditorTheme__ol5",
  //   ],
  //   ul: "PlaygroundEditorTheme__ul",
  // },
  list: {
    checklist: "",
    listitemChecked: "PlaygroundEditorTheme__listItemChecked",
    listitemUnchecked: "PlaygroundEditorTheme__listItemUnchecked",
    nested: {
      listitem: "list-none",
    },
    olDepth: [
      "list-outside list-decimal",
      "m-0 p-0 list-outside list-[upper-alpha]",
      "m-0 p-0 list-outside list-[lower-alpha]",
      "m-0 p-0 list-outside list-[upper-roman]",
      "m-0 p-0 list-outside list-[lower-roman]",
    ],
    ul: "ml-4 space-y-1 list-disc list-outside",
    listitem: "ml-4 marker:text-muted-foreground ",
  },
  ltr: "text-left",
  mark: "PlaygroundEditorTheme__mark",
  markOverlap: "PlaygroundEditorTheme__markOverlap",
  paragraph: "PlaygroundEditorTheme__paragraph",
  quote: "PlaygroundEditorTheme__quote",
  rtl: "text-right",
  table: "PlaygroundEditorTheme__table",
  tableAddColumns: "PlaygroundEditorTheme__tableAddColumns",
  tableAddRows: "PlaygroundEditorTheme__tableAddRows",
  tableCell: "PlaygroundEditorTheme__tableCell",
  tableCellActionButton: "PlaygroundEditorTheme__tableCellActionButton",
  tableCellActionButtonContainer: "PlaygroundEditorTheme__tableCellActionButtonContainer",
  tableCellEditing: "PlaygroundEditorTheme__tableCellEditing",
  tableCellHeader: "PlaygroundEditorTheme__tableCellHeader",
  tableCellPrimarySelected: "PlaygroundEditorTheme__tableCellPrimarySelected",
  tableCellResizer: "PlaygroundEditorTheme__tableCellResizer",
  tableCellSelected: "PlaygroundEditorTheme__tableCellSelected",
  tableCellSortedIndicator: "PlaygroundEditorTheme__tableCellSortedIndicator",
  tableResizeRuler: "PlaygroundEditorTheme__tableCellResizeRuler",
  tableSelected: "PlaygroundEditorTheme__tableSelected",
  tableSelection: "PlaygroundEditorTheme__tableSelection",
  text: {
    bold: "font-bold",
    code: "font-mono text-[94%] bg-secondary p-1 rounded-md",
    italic: "italic",
    strikethrough: "line-through",
    subscript: "sub",
    superscript: "sup",
    underline: "underline",
    underlineStrikethrough: "line-through underline",
  },
};

export default theme;
